CREATE DATABASE PJTDB;

USE PJTDB;

CREATE TABLE SONGS (
ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(25) NOT NULL,
WRITER VARCHAR(20) NOT NULL,
CONTENT TEXT NOT NULL,
VIEWCNT INT DEFAULT 0,
REGDATE TIMESTAMP DEFAULT NOW(),
URL VARCHAR(200) NOT NULL,
IMGURL VARCHAR(200) NOT NULL
);
